# -*- coding: utf-8 -*-
"""ChurnPrediction1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpQRy3DMPH1aDmo7oJrhQ8MdMVJoTJYi
"""

import pandas as pd
import numpy
import matplotlib.pyplot as plt
import seaborn

df = pd.read_csv('/content/Churn.csv')

df.head()

df.drop('Customer ID', axis=1, inplace=True)

df['Total Charges'] = df['Total Charges'].str.strip()
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df['Total Charges'] = df['Total Charges'].fillna(df['Monthly Charges'])

df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

binary_cols = ['Partner', 'Dependents', 'Phone Service', 'Paperless Billing', 'Gender']

df[binary_cols] = df[binary_cols].apply(lambda col: col.map({'Yes': 1, 'No': 0, 'Female': 0, 'Male': 1}))

three_val_cols = ['Multiple Lines', 'Online Security', 'Online Backup',
                  'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies']

df[three_val_cols] = df[three_val_cols].apply(lambda col: col.map(
    {'Yes': 1, 'No': 0, 'No internet service': 0, 'No phone service': 0}
))

df.columns

df.head(15)

df.info()

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

X = df.drop(columns=['Churn'])
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Preprocessor (same for both)
numeric_cols = ['tenure', 'Monthly Charges', 'Total Charges']
categorical_cols = ['Internet Service', 'Contract', 'Payment Method']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(drop='first', handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_cols),
    ('cat', categorical_transformer, categorical_cols)
], remainder='passthrough')

# XGBoost Pipeline
xgb_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', XGBClassifier(scale_pos_weight=5175/1869, random_state=42, eval_metric='logloss'))
])

# Random Forest Pipeline
rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(class_weight='balanced', n_estimators=100, random_state=42))
])

# Train both
xgb_pipeline.fit(X_train, y_train)
rf_pipeline.fit(X_train, y_train)

# Evaluate both
for name, pipeline in [('XGBoost', xgb_pipeline), ('Random Forest', rf_pipeline)]:
    y_pred = pipeline.predict(X_test)
    print(f"\n{'='*40}")
    print(f"  {name}")
    print(f"{'='*40}")
    print(classification_report(y_test, y_pred, target_names=['No Churn', 'Churn']))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

# Lower the decision threshold from default 0.5 to tune precision/recall tradeoff
y_prob = xgb_pipeline.predict_proba(X_test)[:, 1]

# Try different thresholds
for threshold in [0.3, 0.4, 0.5, 0.6]:
    y_pred = (y_prob >= threshold).astype(int)
    print(f"\nThreshold: {threshold}")
    print(classification_report(y_test, y_pred, target_names=['No Churn', 'Churn']))

from sklearn.model_selection import GridSearchCV

params = {
    'model__max_depth': [3, 5, 7],
    'model__learning_rate': [0.01, 0.1, 0.2],
    'model__n_estimators': [100, 200, 300],
    'model__min_child_weight': [1, 3, 5]
}

grid_search = GridSearchCV(xgb_pipeline, params, cv=5, scoring='f1', n_jobs=-1)
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)

print("Best F1 Score:", grid_search.best_score_)
print("Best Params:", grid_search.best_params_)

# Evaluate the best model on test set
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred, target_names=['No Churn', 'Churn']))

import joblib

best_model = grid_search.best_estimator_
joblib.dump(best_model, 'churn_model.pkl')
print("Model saved.")

