# -*- coding: utf-8 -*-
"""SegmentationModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXSP7v9KPVs8EKjXHlP_hhI0DYg7blrb
"""

import pandas as pd
import numpy
import matplotlib.pyplot as plt
import seaborn

df = pd.read_csv('/content/Churn.csv')

df.drop('Customer ID', axis=1, inplace=True)

df['Total Charges'] = df['Total Charges'].str.strip()
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df['Total Charges'] = df['Total Charges'].fillna(df['Monthly Charges'])

df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

binary_cols = ['Partner', 'Dependents', 'Phone Service', 'Paperless Billing', 'Gender']

df[binary_cols] = df[binary_cols].apply(lambda col: col.map({'Yes': 1, 'No': 0, 'Female': 0, 'Male': 1}))

three_val_cols = ['Multiple Lines', 'Online Security', 'Online Backup',
                  'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies']

df[three_val_cols] = df[three_val_cols].apply(lambda col: col.map(
    {'Yes': 1, 'No': 0, 'No internet service': 0, 'No phone service': 0}
))

# Drop duplicates
print("Duplicates:", df.duplicated().sum())
df = df.drop_duplicates().reset_index(drop=True)

# Filter churned customers only
churned_df = df[df['Churn'] == 1].drop(columns=['Churn'])
print("Churned customers shape:", churned_df.shape)
print(churned_df.dtypes)

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import joblib

# Map Contract on churned_df directly
churned_df['Contract'] = churned_df['Contract'].map({
    'Month-to-month': 0,
    'One year': 1,
    'Two year': 2
})

# OHE Internet Service and Payment Method
churned_df = pd.get_dummies(churned_df,
                             columns=['Internet Service', 'Payment Method'],
                             drop_first=True)

# Verify everything is numeric before scaling
print(churned_df.dtypes)
print(churned_df.shape)

# Scale
scaler = StandardScaler()
churned_scaled = scaler.fit_transform(churned_df)
print("Ready for clustering. Shape:", churned_scaled.shape)

# KMeans
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
churned_df['Segment'] = kmeans.fit_predict(churned_scaled)

# Check cluster distribution
print(churned_df['Segment'].value_counts())

# Profile each cluster
print(churned_df.groupby('Segment')[['tenure', 'Monthly Charges', 'Total Charges',
                                      'Contract', 'Senior Citizen']].mean())

# Save models
joblib.dump(kmeans, '/content/data/segmentation_model.pkl')
joblib.dump(scaler, '/content/data/scaler.pkl')

segment_map = {
    0: 'Unsatisfied Churner',
    1: 'Lifestyle Migrator',
    2: 'Conditional Churner'
}

churned_df['Segment Label'] = churned_df['Segment'].map(segment_map)
print(churned_df['Segment Label'].value_counts())

import json

with open('/content/data/segment_map.json', 'w') as f:
    json.dump(segment_map, f)

print("All models saved.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA

# Reduce to 2D for visualization
pca = PCA(n_components=2, random_state=42)
churned_2d = pca.fit_transform(churned_scaled)

# Create a dataframe for plotting
plot_df = pd.DataFrame({
    'PC1': churned_2d[:, 0],
    'PC2': churned_2d[:, 1],
    'Segment': churned_df['Segment'].map({
        0: 'Unsatisfied Churner',
        1: 'Lifestyle Migrator',
        2: 'Conditional Churner'
    })
})

# Plot
plt.figure(figsize=(10, 7))
colors = {
    'Unsatisfied Churner': '#E05C5C',
    'Lifestyle Migrator': '#4A90D9',
    'Conditional Churner': '#5BAD72'
}

for segment, group in plot_df.groupby('Segment'):
    plt.scatter(group['PC1'], group['PC2'],
                label=segment,
                color=colors[segment],
                alpha=0.6,
                s=40)

plt.title('Customer Churn Segments (PCA 2D Projection)', fontsize=14, fontweight='bold')
plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% variance)')
plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% variance)')
plt.legend(title='Segment', fontsize=11)
plt.tight_layout()
plt.savefig('/content/data/segmentation_plot.png', dpi=150)
plt.show()

